services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  elastic:
    image: elasticsearch:8.6.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      # - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
    volumes:
      - data02:/usr/share/elasticsearch/data
    env_file:
      - .env
    ports:
      - 9200:9200


volumes:
  data02: